### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by pgaddam** [pgaddam/sebc#11]

**Comment by pgaddam** [comment]
Complete cluster setup.
But importing sample data was timing out. Cluster was very slow!!!
Included screenshot

**Comment by pgaddam** [comment]
Users were created as captured in 3_cm.md
The slowness in cluster prevented Hue to import sample data

**Comment by pgaddam** [comment]
Seems to be issue with AWS instance used previously. I have created new AWS instances and followed installation. Its gave the results shown the 3_hue_hive.png

New Hosts:
54.219.176.54      ip-172-31-15-77.us-west-1.compute.internal
54.219.150.15      ip-172-31-0-85.us-west-1.compute.internal
54.153.90.105     ip-172-31-14-164.us-west-1.compute.internal
52.53.164.108     ip-172-31-1-172.us-west-1.compute.internal
54.219.137.13      ip-172-31-10-195.us-west-1.compute.internal

**Comment by mfernest** [comment]
That's an unfortunate turn. Sorry to see that happen during an exam.

Completed.
