### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by pgaddam** [pgaddam/sebc#2]

**Comment by mfernest** [comment]
How's your progress so far? 

I noticed just now your Milestones are configured in a funny way. You need one for Labs and one for Challenges -- not each lab stage.

**Comment by pgaddam** [comment]
Complete MySQL replication

**Comment by pgaddam** [comment]
Completed CM installation and committed screen snapshot to labs folder

**Comment by mfernest** [comment]
Completed
