### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by pgaddam** [pgaddam/sebc#3]

**Comment by pgaddam** [comment]
Complete Terasort test

**Comment by pgaddam** [comment]
Competed HA and CM User
http://52.53.247.180:7180/cmf/home

**Comment by pgaddam** [comment]
Completed Test HDFS Snapshots

**Comment by pgaddam** [comment]
Complete HDFS Replication from @jastidinesh cluster

**Comment by mfernest** [comment]
How does `3_HDFS_HA.png` show that HA is configured?

Completed.
